
% loop through 12 main plot categories folders
categories = dir('first-plot/');
category_folders = categories([categories(:).isdir]); 
category_folders = category_folders(~ismember({category_folders(:).name},{'.','..'}));
for k = 1 : 2% length(category_folders)
    fprintf('Sub folder #%d = %s\n', k, category_folders(k).name);
    
    % loop through every plot in the main plot category
    folder = fullfile(category_folders(k).folder, category_folders(k).name, "*.m");
    plot_files = dir(folder);
    for j = 1 : length(plot_files)
        fprintf('-----#%d = %s\n', j, plot_files(j).name);
        % run the content of the file
        % they all include the full script required to complete
        % this was generated by Python script
        plot = fullfile(category_folders(k).folder, category_folders(k).name, plot_files(j).name);
        run(plot())
        pause(2)
    end
end
